---
title: "Bugs, Pipeline, and Dashboard"
author: "Hayden Wilcox"
date: "2026-07-06"
categories: [python, sql, data-engineering, etl]
---

## Resolving Bugs/Connection Issues

This was the part that took the longest, as many adjustments had to be made for the formatting of the pipeline to go into Polars. Additionally, I had to spend some time setting up Docker to be able to run PostgreSQL after fixing the pipeline's issues. It ran fine afterwards and I was able to get what I needed. Witho the amount of data that Seattle contains, it's worth considering using something like MangoDB or DuckDB to run ALL of the data. For time's sake, I'm leaving it as is, but this will be worth looking into later on for optimization purposes.

## Dashboard

After wrapping up with those fixes, I began work on getting a dashboard with the basic crime analytics needed. Even though I'm still not 100% familiar with navigating Metabase's system and UI, I found that producing general analyitcs for my data was relatively simple. For example, we almost immediately visualize property crime as the most common category. We have a map with all the points automatically highlighted at the top as well. This is like a small sample of what we'll do in our GIS work.






